language: node_js

# test on different versions of node.js
node_js:
    - 6.10.3
    - 7.10.0

# configure notifications
notifications:
    email:
        recipients:
          - maurizio.cescon@gmail.com
        on_success: change # default: change
        on_failure: always # default: always
