language: node_js

# test on different versions of node.js
node_js:
  - 12.13.1
  - 13.3.0

# addition of chrome for testing
addons:
  chrome: stable

# configure notifications
notifications:
  email:
    recipients:
      - maurizio.cescon@gmail.com
    on_success: change # default: change
    on_failure: always # default: always
