language: node_js

# test on different versions of node.js
node_js:
    - 8.11.2
    - 10.4.0

# configure notifications
notifications:
    email:
        recipients:
          - maurizio.cescon@gmail.com
        on_success: change # default: change
        on_failure: always # default: always
