language: node_js

# test on different versions of node.js
node_js:
    - 6.10.2
    - 7.9.0

# configure notifications
notifications:
    email:
        recipients:
          - maurizio.cescon@gmail.com
        on_success: always # default: change
        on_failure: always # default: always